version: '3.7'

services:
  localstack:
    container_name: order-book-api
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,dynamodbstreams
      - DEBUG=${DEBUG-}
      - PORT-WEB-UI=${PORT_WEB_UI-}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/docker-entrypoint-initaws.d"